server:
  port: 9090 # The public-facing port for our entire system

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Route requests for the investment-service
            - id: investment-service-route # A unique ID for this route
              uri: lb://investment-service # "lb" stands for load-balanced. Routes to the service named "investment-service"
              predicates:
                - Path=/api/** # Match any request starting with /api/ and forward it
              #filters:
                 # Remove the first path segment (/api/investments) before forwarding
                #- StripPrefix=2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}} # Create unique IDs if multiple instances run

jwt:
  # This is a default secret key for development.
  # In a production environment, this MUST be overridden with a strong, securely-stored secret,
  # for example, via environment variables or a configuration server.
  # A good practice is to use a long, randomly generated string.
  # You can generate one here: https://www.allkeysgenerator.com/Random/Security-Encryption-Key-Generator.aspx
  secret: "413F4428472B4B6250655368566D5970337336763979244226452948404D6351"
  expiration:
    # Token validity in milliseconds. 900000ms = 15 minutes
    ms: 900000