spring.application.name=fintrackr

# By default, activate the 'dev' profile for local development.
# This can be overridden by an environment variable in other environments.
spring.profiles.active=dev

# --- Common Properties for ALL Profiles ---

# PostgreSQL Database Connection
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
