spring:
  datasource:
    # Use the service name 'user-db' as the hostname within the Docker network
    url: jdbc:postgresql://user-db:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka
