server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:fintrackr_user_db}
    username: ${DB_USER:fintrackr_userdb_user}
    password: ${DB_PASSWORD:fintrackr_userdb_password}
  jpa:
    hibernate:
      ddl-auto: validate # Flyway handles schema creation, so Hibernate should only validate it
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}} # Create unique IDs if multiple instances run

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

fintrackr:
  jwt:
    secret: V2VsbCBIZWxsbyBUaGVyZSEgVGhpcyBpcyBhIFRlc3RpbmcgU2VjcmV0IEtleSBGb3IgSldUIFNpZ25pbmc=
    accesstoken:
      expiration: 1h # 1 hour
    refreshtoken:
      expiration: 7d # 7 days