name: Java CI with Maven

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ] # Runs on pushes to the main branch
  pull_request:
    branches: [ "main" ] # Runs on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest # The type of runner that the job will run on

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven' # Cache Maven dependencies for faster builds

    - name: Build with Maven
      run: mvn -B verify --file investment-service/pom.xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./investment-service/target/site/jacoco/jacoco.xml
        fail_ci_if_error: true
