name: Java CI with Maven

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Log triggering event
        run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      
      - name: Log runner info
        run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"

      - name: Log branch and repo info
        run: echo "The name of the branch is ${{ github.ref }} and the repository is ${{ github.repository }}."

      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven
          
      - name: Build and Test with Maven
        run: mvn -B verify
        env:
          # Tell Spring to use the 'test' profile
          SPRING_PROFILES_ACTIVE: test
          # Securely inject the password from GitHub Secrets
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}